org: armynante
app: baedek 
service: scrape-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript


functions:
  api:
    handler: handler.handler
    timeout: 30
    memorySize: 3008 
    events:
      - httpApi: '*'
